[package]
name = "speech-to-text-remote"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stt-remote"
path = "main.rs"

[dependencies]
reqwest = { workspace = true, features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
